### ISSUE TITLE
qsprpred.scorers not found

### ISSUE THREAD

**Issue by zemanet2020** [CDDLeiden/DrugEx#1]
train.py in  drugex  uses qsprpred.scorers module, but there is no scorers module in qsprpred.

> python --version
Python 3.9.16

> echo 'import qsprpred;print(qsprpred.__version__)' | python
1.2.0

> echo 'import drugex;print(drugex.__version__)' | python
3.4.0

======================================================================
  File "DrugEx/drugex/train.py", line 29, in <module>
    from qsprpred.scorers.predictor import Predictor
ModuleNotFoundError: No module named 'qsprpred.scorers'

**Comment by martin-sicho** [comment]
Hi @zemanet2020,

thanks for the interest in DrugEx! That script still needs to be updated to the new QSPRPred interface in `1.2.0`, but we are already working on it and will update this very soon. I will let you know here when that is available (either this or next week). In the meantime, you can use the Python API (see [tutorial](../tree/master/tutorial)).

**Comment by martin-sicho** [comment]
@zemanet2020 

This should now be fixed in `v3.4.1`. Make sure you also use `qsprpred==v1.3.0` with that update.
