### ISSUE TITLE
CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by pritam0070** [CDDLeiden/DrugEx#11]
RuntimeError: CUDA error: invalid device ordinal
Compile with `TORCH_USE_CUDA_DSA`to enable device-side assertions.

when I try to run `python -m drugex.generate -b ${BASE_DIR} -i arl_test_graph.txt -g arl_graph_trans_RL` this comment I got above error.

### Device Description
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Jan__6_16:45:21_PST_2023
Cuda compilation tools, release 12.0, V12.0.140
Build cuda_12.0.r12.0/compiler.32267302_0
Torch Version : 2.5.1+cu124

**Comment by martin-sicho** [comment]
Hi, I am not that familiar with the CLI, but maybe you should specify the GPU(S) you want to use explicitly. That is done with the `-gpu` parameter. I think that the default value assumes multiple GPUs to be installed. So you might want to change that to someting like `-gpu 0` if your system only has one. You can display the help menu with `drugex generate -h` or `python -m drugex.generate -h`.

**Comment by pritam0070** [comment]
Thank you, with `gpu 0` , it runs without giving error.
