### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by adlvdl** [CDDLeiden/DrugEx#3]
On the README of this repository it is said that the software is free for academic use but any commercial use needs to first be agreed with the authors. However, that seems to run counter to the license provided in the repository, the MIT license, which allows for use in commercial software so long as attribution is made clear and the license terms are reshared. If it is indeed the case that you want to restrict use in commercial setting, you should change the license to a more restrictive one.

**Comment by martin-sicho** [comment]
Hi, sorry for the delay. We had to clarify some things first and it dragged on over the holidays. 

DrugEx is indeed licensed under full MIT license, which is provided with the repository. We removed the confusing statement from the readme file in the current release. Thank you for bringing this up to our attention!
