### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by shuvadipkhanra** [CDDLeiden/DrugEx#9]
pip install git+https://github.com/CDDLeiden/DrugEx.git@master
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/CDDLeiden/DrugEx.git@master
  Cloning https://github.com/CDDLeiden/DrugEx.git (to revision master) to /tmp/pip-req-build-y1eadsmo
  Running command git clone --filter=blob:none --quiet https://github.com/CDDLeiden/DrugEx.git /tmp/pip-req-build-y1eadsmo
  Resolved https://github.com/CDDLeiden/DrugEx.git to commit 34687de0205f4cbe178786b8378dca8babbd4bfe
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-3.4.7-py3-none-any.whl size=1777 sha256=376238adc6f3a2d5ea73ce8c075295ed09502ba994ad7deaa243f3a2313ad08d
  Stored in directory: /tmp/pip-ephem-wheel-cache-zv9_t9my/wheels/fe/3b/66/01b41b1d4e82261cf810dfa79d1417c7d06c7aefc4da466c8c
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
Successfully installed UNKNOWN-3.4.7

pip install "drugex[qsprpred] @ git+https://github.com/CDDLeiden/DrugEx.git@master"
Defaulting to user installation because normal site-packages is not writeable
Collecting drugex[qsprpred]@ git+https://github.com/CDDLeiden/DrugEx.git@master
  Cloning https://github.com/CDDLeiden/DrugEx.git (to revision master) to /tmp/pip-install-0w8i1v_a/drugex_cf503470be1d4555adaeae273a57fa30
  Running command git clone --filter=blob:none --quiet https://github.com/CDDLeiden/DrugEx.git /tmp/pip-install-0w8i1v_a/drugex_cf503470be1d4555adaeae273a57fa30
  Resolved https://github.com/CDDLeiden/DrugEx.git to commit 34687de0205f4cbe178786b8378dca8babbd4bfe
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package drugex produced metadata for project name unknown. Fix your #egg=drugex fragments.
Discarding git+https://github.com/CDDLeiden/DrugEx.git@master: Requested unknown from git+https://github.com/CDDLeiden/DrugEx.git@master has inconsistent name: filename has 'drugex', but metadata has 'unknown'
ERROR: Could not find a version that satisfies the requirement drugex (unavailable) (from versions: none)
ERROR: No matching distribution found for drugex (unavailable)

**Comment by HellevdM** [comment]
Hi,

Thank you for letting us know about the issue.
I tried reproducing the error, but the "pip install git+https://github.com/CDDLeiden/DrugEx.git@master",
ran successfully for me. From the error, it seems like it might be a permission issue.
Which python version are you using?
Perhaps you could also try creating a clean environment (e.g. conda environment) and check if that fixes the issue.

**Comment by pritam0070** [comment]
Can you refer a suitable Python version for the installation of DrugEx ?

**Comment by martin-sicho** [comment]
@pritam0070 I think it should work fine on versions >= 3.10. I am using it on 3.11 without problems, for example. I would also recommend to use a conda environment since the original error by @shuvadipkhanra mentions `Defaulting to user installation because normal site-packages is not writeable`, which indicates a problem with permissions so using a virtualenv or a conda environment in the user space should solve that as well.
